<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {       
        // Aseguramos que existan categorías
        if (Category::count() == 0) {
            $this->command->warn('⚠️ No hay categorías creadas. Ejecuta CategorySeeder primero.');
            return;
        }

        // Obtenemos categorías existentes
        $dragonBallId = Category::where('nombre', 'Dragon Ball')->value('id');
        $narutoId = Category::where('nombre', 'Naruto')->value('id');
        $onePieceId = Category::where('nombre', 'One Piece')->value('id');
        $marvelDcId = Category::where('nombre', 'Marvel & DC')->value('id');
        $pokemonId = Category::where('nombre', 'Pokémon')->value('id');
        $harryPotterId = Category::where('nombre', 'Harry Potter')->value('id');
        $demonSlayerId = Category::where('nombre', 'Demon Slayer')->value('id');
        $seriesCaricaturasId = Category::where('nombre', 'Series y caricaturas')->value('id');
        $otrosAnimesId = Category::where('nombre', 'Otros animes/series')->value('id');
        $starWarsId = Category::where('nombre', 'Star Wars')->value('id');

        $now = Carbon::now();

        $products = [
            // DRAGON BALL - 25 productos
            [
                'sku' => 'DB-001',
                'nombre' => 'GOKU SUPER SAYAYIN',
                'slug' => Str::slug('GOKU SUPER SAYAYIN'),
                'descripcion' => 'Figura de Goku Super Sayayin. Tamaño 18 cm, material PVC. Incluye base más aros de poder.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '18 cm',
                'incluye' => 'BASE MÁS AROS DE PODER',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-002',
                'nombre' => 'GOKU EN MOTOCICLETA',
                'slug' => Str::slug('GOKU EN MOTOCICLETA'),
                'descripcion' => 'Figura de Goku en motocicleta. Tamaño 13 cm, material PVC.',
                'precio' => 50.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '13 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-003',
                'nombre' => 'GOKU CON BASE Y BACULOS',
                'slug' => Str::slug('GOKU CON BASE Y BACULOS'),
                'descripcion' => 'Figura de Goku. Tamaño 20 cm, material PVC. Incluye base circular más 2 báculos.',
                'precio' => 39.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-003.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '20 cm',
                'incluye' => 'BASE CIRCULAR MÁS 2 BÁCULOS',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-004',
                'nombre' => 'ANDROIDE N° 17',
                'slug' => Str::slug('ANDROIDE N° 17'),
                'descripcion' => 'Figura del Androide N° 17. Tamaño 24 cm, material PVC.',
                'precio' => 45.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-004.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '24 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-005',
                'nombre' => 'ANDROIDE N° 18',
                'slug' => Str::slug('ANDROIDE N° 18'),
                'descripcion' => 'Figura del Androide N° 18. Tamaño 23 cm, material PVC.',
                'precio' => 45.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-005.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '23 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-006',
                'nombre' => 'GOKU SUPER SAYAYIN 16CM',
                'slug' => Str::slug('GOKU SUPER SAYAYIN 16CM'),
                'descripcion' => 'Figura de Goku Super Sayayin. Tamaño 16 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-006.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '16 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-007',
                'nombre' => 'BILLS DRAGON BALL',
                'slug' => Str::slug('BILLS DRAGON BALL'),
                'descripcion' => 'Figura de Bills. Tamaño 30 cm, material PVC. Incluye base.',
                'precio' => 59.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-007.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '30 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-008',
                'nombre' => 'FREEZER DRAGON BALL',
                'slug' => Str::slug('FREEZER DRAGON BALL'),
                'descripcion' => 'Figura de Freezer. Tamaño 22 cm, material PVC.',
                'precio' => 55.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-008.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '22 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-009',
                'nombre' => 'TRUNKS CON ESPADA',
                'slug' => Str::slug('TRUNKS CON ESPADA'),
                'descripcion' => 'Figura de Trunks. Tamaño 21 cm, material PVC. Incluye espada.',
                'precio' => 39.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-009.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '21 cm',
                'incluye' => 'ESPADA',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-010',
                'nombre' => 'BULMA CON BASE CIRCULAR',
                'slug' => Str::slug('BULMA CON BASE CIRCULAR'),
                'descripcion' => 'Figura de Bulma. Tamaño 18 cm, material PVC. Incluye base circular.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-010.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '18 cm',
                'incluye' => 'BASE CIRCULAR',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-011',
                'nombre' => 'VEGETA DRAGON BALL',
                'slug' => Str::slug('VEGETA DRAGON BALL'),
                'descripcion' => 'Figura de Vegeta. Tamaño 21 cm, material PVC.',
                'precio' => 39.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-011.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '21 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-012',
                'nombre' => 'MAESTRO ROSHI',
                'slug' => Str::slug('MAESTRO ROSHI'),
                'descripcion' => 'Figura del Maestro Roshi. Tamaño 10 cm, material PVC.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-012.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '10 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-013',
                'nombre' => 'TRUNKS 27CM',
                'slug' => Str::slug('TRUNKS 27CM'),
                'descripcion' => 'Figura de Trunks. Tamaño 27 cm, material PVC.',
                'precio' => 55.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-013.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '27 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-014',
                'nombre' => 'KRILIN DRAGON BALL',
                'slug' => Str::slug('KRILIN DRAGON BALL'),
                'descripcion' => 'Figura de Krilin. Tamaño 16.5 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-014.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '16.5 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-015',
                'nombre' => 'GOHAN DRAGON BALL',
                'slug' => Str::slug('GOHAN DRAGON BALL'),
                'descripcion' => 'Figura de Gohan. Tamaño 16 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-015.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '16 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-016',
                'nombre' => 'BOO DRAGON BALL',
                'slug' => Str::slug('BOO DRAGON BALL'),
                'descripcion' => 'Figura de Boo. Tamaño 25 cm, material PVC.',
                'precio' => 39.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-016.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '25 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-017',
                'nombre' => 'SHENGLONG CON ESFERAS',
                'slug' => Str::slug('SHENGLONG CON ESFERAS'),
                'descripcion' => 'Figura de Shenglong. Tamaño 18 cm, material PVC. Incluye base circular más 7 esferas pequeñas.',
                'precio' => 55.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-017.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '18 cm',
                'incluye' => 'BASE CIRCULAR MÁS 7 ESFERAS PEQUEÑAS',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-018',
                'nombre' => 'BROLY CON BASE CIRCULAR',
                'slug' => Str::slug('BROLY CON BASE CIRCULAR'),
                'descripcion' => 'Figura de Broly. Tamaño 20 cm, material PVC. Incluye base circular.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-018.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '20 cm',
                'incluye' => 'BASE CIRCULAR',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-019',
                'nombre' => '8 TRANSFORMACIONES DE FREEZER',
                'slug' => Str::slug('8 TRANSFORMACIONES DE FREEZER'),
                'descripcion' => 'Set de 8 transformaciones de Freezer. Tamaño 8-12 cm, material PVC.',
                'precio' => 59.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-019.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8-12 cm',
                'incluye' => '8 FIGURAS',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-020',
                'nombre' => '8 TRANSFORMACIONES DE MAJIN BOO',
                'slug' => Str::slug('8 TRANSFORMACIONES DE MAJIN BOO'),
                'descripcion' => 'Set de 8 transformaciones de Majin Boo. Tamaño 8-12 cm, material PVC.',
                'precio' => 59.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-020.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8-12 cm',
                'incluye' => '8 FIGURAS',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-021',
                'nombre' => 'SET 5 FIGURAS DE BOO',
                'slug' => Str::slug('SET 5 FIGURAS DE BOO'),
                'descripcion' => 'Set of 5 Boo figures. Tamaño 8 cm, material PVC.',
                'precio' => 50.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-021.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => '5 FIGURAS',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-022',
                'nombre' => 'GOKU Y PUAR',
                'slug' => Str::slug('GOKU Y PUAR'),
                'descripcion' => 'Figura de Goku y Puar. Tamaño 11 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-022.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '11 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-023',
                'nombre' => 'GOKU 9CM',
                'slug' => Str::slug('GOKU 9CM'),
                'descripcion' => 'Figura de Goku. Tamaño 9 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-023.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '9 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-024',
                'nombre' => 'GOKU Y MAESTRO KARIN',
                'slug' => Str::slug('GOKU Y MAESTRO KARIN'),
                'descripcion' => 'Figura de Goku y Maestro Karin. Tamaño 12 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-024.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DB-025',
                'nombre' => 'GOKU 10CM',
                'slug' => Str::slug('GOKU 10CM'),
                'descripcion' => 'Figura de Goku. Tamaño 10 cm, material PVC.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/db-025.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '10 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $dragonBallId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // NARUTO - 2 productos
            [
                'sku' => 'NAR-001',
                'nombre' => 'NARUTO CON BASE Y BANDERA',
                'slug' => Str::slug('NARUTO CON BASE Y BANDERA'),
                'descripcion' => 'Figura de Naruto. Tamaño 12 cm, material PVC. Incluye base y bandera.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/nar-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => 'BASE Y BANDERA',
                'activo' => true,
                'category_id' => $narutoId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'NAR-002',
                'nombre' => 'NARUTO SET DE 6 FIGURAS',
                'slug' => Str::slug('NARUTO SET DE 6 FIGURAS'),
                'descripcion' => 'Set de 6 figuras de Naruto. Tamaño 8 cm, material PVC. Incluye base.',
                'precio' => 40.00,
                'stock' => 5,
                'imagen1' => 'images/products/nar-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => '6 FIGURAS CON BASE',
                'activo' => true,
                'category_id' => $narutoId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ONE PIECE - 12 productos
            [
                'sku' => 'OP-001',
                'nombre' => 'LUFFY 17CM',
                'slug' => Str::slug('LUFFY 17CM'),
                'descripcion' => 'Figura de Luffy. Tamaño 17 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '17 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-002',
                'nombre' => 'LUFFY 17.5X12.5CM',
                'slug' => Str::slug('LUFFY 17.5X12.5CM'),
                'descripcion' => 'Figura de Luffy. Tamaño 17.5x12.5 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '17.5x12.5 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-003',
                'nombre' => 'LUFFY 10CM',
                'slug' => Str::slug('LUFFY 10CM'),
                'descripcion' => 'Figura de Luffy. Tamaño 10 cm, material PVC. Incluye base.',
                'precio' => 24.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-003.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '10 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-004',
                'nombre' => 'LUFFY 18CM',
                'slug' => Str::slug('LUFFY 18CM'),
                'descripcion' => 'Figura de Luffy. Tamaño 18 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-004.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '18 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-005',
                'nombre' => 'LUFFY 24CM',
                'slug' => Str::slug('LUFFY 24CM'),
                'descripcion' => 'Figura de Luffy. Tamaño 24 cm, material PVC.',
                'precio' => 45.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-005.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '24 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-006',
                'nombre' => 'LUFFY 12CM',
                'slug' => Str::slug('LUFFY 12CM'),
                'descripcion' => 'Figura de Luffy. Tamaño 12 cm, material PVC.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-006.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-007',
                'nombre' => 'ZORO CON ESPADAS',
                'slug' => Str::slug('ZORO CON ESPADAS'),
                'descripcion' => 'Figura de Zoro. Tamaño 12 cm, material PVC. Incluye base + 3 espadas con rayos de poder.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-007.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => 'BASE + 3 ESPADAS CON RAYOS DE PODER',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-008',
                'nombre' => 'ZORO 16.5X12.5CM',
                'slug' => Str::slug('ZORO 16.5X12.5CM'),
                'descripcion' => 'Figura de Zoro. Tamaño 16.5x12.5 cm, material PVC. Incluye base + 3 espadas.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-008.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '16.5x12.5 cm',
                'incluye' => 'BASE + 3 ESPADAS',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-009',
                'nombre' => 'SANJI ONE PIECE',
                'slug' => Str::slug('SANJI ONE PIECE'),
                'descripcion' => 'Figura de Sanji. Tamaño 12x15 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-009.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12x15 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-010',
                'nombre' => 'ACE ONE PIECE',
                'slug' => Str::slug('ACE ONE PIECE'),
                'descripcion' => 'Figura de Ace. Tamaño 12 cm, material PVC. Incluye base.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-010.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-011',
                'nombre' => 'SET DE 6 FIGURAS DE ONE PIECE',
                'slug' => Str::slug('SET DE 6 FIGURAS DE ONE PIECE'),
                'descripcion' => 'Set de 6 figuras de One Piece. Tamaño 8 cm, material PVC. Cada uno viene con base circular.',
                'precio' => 49.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-011.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => '6 FIGURAS CON BASE CIRCULAR',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OP-012',
                'nombre' => 'ARALE CON BASE CIRCULAR',
                'slug' => Str::slug('ARALE CON BASE CIRCULAR'),
                'descripcion' => 'Figura de Arale. Tamaño 15 cm, material PVC. Incluye base circular.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/op-012.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '15 cm',
                'incluye' => 'BASE CIRCULAR',
                'activo' => true,
                'category_id' => $onePieceId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // MARVEL & DC - 7 productos
            [
                'sku' => 'MV-001',
                'nombre' => 'IRON MAN',
                'slug' => Str::slug('IRON MAN'),
                'descripcion' => 'Figura de Iron Man. Tamaño 12 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'MV-002',
                'nombre' => 'SPIDER MAN',
                'slug' => Str::slug('SPIDER MAN'),
                'descripcion' => 'Figura de Spider Man. Tamaño 12 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '12 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'MV-003',
                'nombre' => 'CAPITAN AMERICA',
                'slug' => Str::slug('CAPITAN AMERICA'),
                'descripcion' => 'Figura de Capitán América. Tamaño 13 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-003.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '13 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'MV-004',
                'nombre' => 'SET 3 FIGURAS MARVEL',
                'slug' => Str::slug('SET 3 FIGURAS MARVEL'),
                'descripcion' => 'Set de 3 figuras de Marvel. Tamaño 3.5-10.5 cm, material PVC.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-004.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '3.5-10.5 cm',
                'incluye' => '3 FIGURAS',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'MV-005',
                'nombre' => 'SET 4 SPIDER MAN',
                'slug' => Str::slug('SET 4 SPIDER MAN'),
                'descripcion' => 'Set de 4 figuras de Spider Man. Tamaño 6-8 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-005.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '6-8 cm',
                'incluye' => '4 FIGURAS CON BASE',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'MV-006',
                'nombre' => 'SUPER MAN',
                'slug' => Str::slug('SUPER MAN'),
                'descripcion' => 'Figura de Super Man. Tamaño 15 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-006.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '15 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'MV-007',
                'nombre' => 'PSYDUCK CELL',
                'slug' => Str::slug('PSYDUCK CELL'),
                'descripcion' => 'Figura de Psyduck Cell. Tamaño 9 cm, material PVC. Casco desmontable.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/mv-007.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '9 cm',
                'incluye' => 'CASCO DESMONTABLE',
                'activo' => true,
                'category_id' => $marvelDcId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // POKEMON - 9 productos
            [
                'sku' => 'PK-001',
                'nombre' => 'POKEBOLA 24 POKEMON',
                'slug' => Str::slug('POKEBOLA 24 POKEMON'),
                'descripcion' => 'Pokebola con 24 pokemons. Tamaño pokebola: 7x7 cm, pokemons: 3 cm.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => 'Pokebola: 7x7 cm, Pokemons: 3 cm',
                'incluye' => 'POKEBOLA + 24 POKEMONS',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-002',
                'nombre' => 'SET 6 SNORLAX',
                'slug' => Str::slug('SET 6 SNORLAX'),
                'descripcion' => 'Set de 6 figuras de Snorlax. Tamaño 3.5 cm, material PVC.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '3.5 cm',
                'incluye' => '6 FIGURAS',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-003',
                'nombre' => 'LAMPARA PIKACHU',
                'slug' => Str::slug('LAMPARA PIKACHU'),
                'descripcion' => 'Lámpara de Pikachu. Pikachu boca arriba 13 cm, boca abajo 11 cm. Funcionan a pila.',
                'precio' => 28.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-003.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '13 cm / 11 cm',
                'incluye' => 'LÁMPARA FUNCIONAL',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-004',
                'nombre' => 'CUBONE POKEMON',
                'slug' => Str::slug('CUBONE POKEMON'),
                'descripcion' => 'Figura de Cubone. Tamaño 8 cm, material PVC.',
                'precio' => 24.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-004.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-005',
                'nombre' => 'BULBASAUR CON ALMOHADA',
                'slug' => Str::slug('BULBASAUR CON ALMOHADA'),
                'descripcion' => 'Figura de Bulbasaur con almohada. Tamaño 8 cm, material PVC. Incluye almohada.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-005.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => 'ALMOHADA',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-006',
                'nombre' => 'SNORLAX CON ALMOHADA',
                'slug' => Str::slug('SNORLAX CON ALMOHADA'),
                'descripcion' => 'Figura de Snorlax con almohada. Tamaño 8 cm, material PVC. Incluye almohada.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-006.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => 'ALMOHADA',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-007',
                'nombre' => 'PIKACHU CON ALMOHADA',
                'slug' => Str::slug('PIKACHU CON ALMOHADA'),
                'descripcion' => 'Figura de Pikachu con almohada. Tamaño 8 cm, material PVC. Incluye almohada.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-007.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => 'ALMOHADA',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-008',
                'nombre' => 'EEVEE CON ALMOHADA',
                'slug' => Str::slug('EEVEE CON ALMOHADA'),
                'descripcion' => 'Figura de Eevee con almohada. Tamaño 8 cm, material PVC. Incluye almohada.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-008.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => 'ALMOHADA',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'PK-009',
                'nombre' => 'JIRACHI CON ALMOHADA',
                'slug' => Str::slug('JIRACHI CON ALMOHADA'),
                'descripcion' => 'Figura de Jirachi con almohada. Tamaño 8 cm, material PVC. Incluye almohada.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/pk-009.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => 'ALMOHADA',
                'activo' => true,
                'category_id' => $pokemonId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // HARRY POTTER - 1 producto
            [
                'sku' => 'HP-001',
                'nombre' => 'SET 3 FIGURAS HARRY POTTER',
                'slug' => Str::slug('SET 3 FIGURAS HARRY POTTER'),
                'descripcion' => 'Set de 3 figuras de Harry Potter. Tamaño 10 cm, material PVC. Todas vienen con base circular.',
                'precio' => 45.00,
                'stock' => 5,
                'imagen1' => 'images/products/hp-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '10 cm',
                'incluye' => '3 FIGURAS CON BASE CIRCULAR',
                'activo' => true,
                'category_id' => $harryPotterId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // DEMON SLAYER - 2 productos
            [
                'sku' => 'DS-001',
                'nombre' => 'SET 10 FIGURAS DEMON SLAYER',
                'slug' => Str::slug('SET 10 FIGURAS DEMON SLAYER'),
                'descripcion' => 'Set de 10 figuras de Demon Slayer. Tamaño 5 cm, material PVC. Cada uno viene con base circular.',
                'precio' => 65.00,
                'stock' => 5,
                'imagen1' => 'images/products/ds-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '5 cm',
                'incluye' => '10 FIGURAS CON BASE CIRCULAR',
                'activo' => true,
                'category_id' => $demonSlayerId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'DS-002',
                'nombre' => 'SET 6 FIGURAS DEMON SLAYER',
                'slug' => Str::slug('SET 6 FIGURAS DEMON SLAYER'),
                'descripcion' => 'Set de 6 figuras de Demon Slayer. Tamaño 8 cm, material PVC. Todas vienen con base circular.',
                'precio' => 40.00,
                'stock' => 5,
                'imagen1' => 'images/products/ds-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => '6 FIGURAS CON BASE CIRCULAR',
                'activo' => true,
                'category_id' => $demonSlayerId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // SERIES Y CARICATURAS - 10 productos
            [
                'sku' => 'SC-001',
                'nombre' => 'SET 6 FIGURAS BOB ESPONJA',
                'slug' => Str::slug('SET 6 FIGURAS BOB ESPONJA'),
                'descripcion' => 'Set de 6 figuras de Bob Esponja. Tamaño 5-6 cm, material PVC.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '5-6 cm',
                'incluye' => '6 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-002',
                'nombre' => 'SET 6 FIGURAS MICKEY MOUSE',
                'slug' => Str::slug('SET 6 FIGURAS MICKEY MOUSE'),
                'descripcion' => 'Set de 6 figuras de Mickey Mouse. Tamaño 6 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '6 cm',
                'incluye' => '6 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-003',
                'nombre' => 'SET 9 FIGURAS DIGIMON',
                'slug' => Str::slug('SET 9 FIGURAS DIGIMON'),
                'descripcion' => 'Set de 9 figuras de Digimon. Tamaño 4-5 cm, material PVC.',
                'precio' => 40.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-003.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '4-5 cm',
                'incluye' => '9 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-004',
                'nombre' => 'TOY STORY SET 8 FIGURAS',
                'slug' => Str::slug('TOY STORY SET 8 FIGURAS'),
                'descripcion' => 'Set de 8 figuras de Toy Story. Tamaño 4-5 cm, material PVC.',
                'precio' => 40.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-004.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '4-5 cm',
                'incluye' => '8 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-005',
                'nombre' => 'SET 10 FIGURAS PELICULAS TERROR',
                'slug' => Str::slug('SET 10 FIGURAS PELICULAS TERROR'),
                'descripcion' => 'Set de 10 figuras de películas de terror. Tamaño 5 cm, material PVC. Cada uno viene con base circular.',
                'precio' => 59.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-005.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '5 cm',
                'incluye' => '10 FIGURAS CON BASE CIRCULAR',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-006',
                'nombre' => 'SUPER MARIO BROS SET 6 FIGURAS',
                'slug' => Str::slug('SUPER MARIO BROS SET 6 FIGURAS'),
                'descripcion' => 'Set de 6 figuras de Super Mario Bros. Tamaño 4-6 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-006.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '4-6 cm',
                'incluye' => '6 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-007',
                'nombre' => 'TOM Y JERRY SET 4 FIGURAS',
                'slug' => Str::slug('TOM Y JERRY SET 4 FIGURAS'),
                'descripcion' => 'Set de 4 figuras de Tom y Jerry. Tamaño 5 cm, material PVC.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-007.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '5 cm',
                'incluye' => '4 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-008',
                'nombre' => 'SET 9 FIGURAS INTENSAMENTE',
                'slug' => Str::slug('SET 9 FIGURAS INTENSAMENTE'),
                'descripcion' => 'Set de 9 figuras de Intensamente. Tamaño 4-5 cm, material PVC.',
                'precio' => 45.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-008.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '4-5 cm',
                'incluye' => '9 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-009',
                'nombre' => 'SET 6 FIGURAS LILO Y STITCH',
                'slug' => Str::slug('SET 6 FIGURAS LILO Y STITCH'),
                'descripcion' => 'Set de 6 figuras de Lilo y Stitch. Tamaño 2 cm, material PVC.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-009.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '2 cm',
                'incluye' => '6 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SC-010',
                'nombre' => 'SET 12 FIGURAS LILO Y STITCH',
                'slug' => Str::slug('SET 12 FIGURAS LILO Y STITCH'),
                'descripcion' => 'Set de 12 figuras de Lilo y Stitch. Tamaño 2-3 cm, material PVC.',
                'precio' => 39.00,
                'stock' => 5,
                'imagen1' => 'images/products/sc-010.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '2-3 cm',
                'incluye' => '12 FIGURAS',
                'activo' => true,
                'category_id' => $seriesCaricaturasId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // OTROS ANIMES/SERIES - 4 productos
            [
                'sku' => 'OA-001',
                'nombre' => 'YU GIOH',
                'slug' => Str::slug('YU GIOH'),
                'descripcion' => 'Figura de Yu Gioh. Tamaño 13 cm, material PVC.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/oa-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '13 cm',
                'incluye' => '',
                'activo' => true,
                'category_id' => $otrosAnimesId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OA-002',
                'nombre' => 'DEATH NOTE FIGURA',
                'slug' => Str::slug('DEATH NOTE FIGURA'),
                'descripcion' => 'Figura de Death Note. Tamaño 24 cm, material PVC. Incluye base más alas.',
                'precio' => 39.00,
                'stock' => 5,
                'imagen1' => 'images/products/oa-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '24 cm',
                'incluye' => 'BASE MÁS ALAS',
                'activo' => true,
                'category_id' => $otrosAnimesId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OA-003',
                'nombre' => 'SALOR MOON CON BASE',
                'slug' => Str::slug('SALOR MOON CON BASE'),
                'descripcion' => 'Figura de Salor Moon. Tamaño 16 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/oa-003.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '16 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $otrosAnimesId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'OA-004',
                'nombre' => 'SALOR MOON 16CM',
                'slug' => Str::slug('SALOR MOON 16CM'),
                'descripcion' => 'Figura de Salor Moon. Tamaño 16 cm, material PVC. Incluye base.',
                'precio' => 35.00,
                'stock' => 5,
                'imagen1' => 'images/products/oa-004.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '16 cm',
                'incluye' => 'BASE',
                'activo' => true,
                'category_id' => $otrosAnimesId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // STAR WARS - 2 productos
            [
                'sku' => 'SW-001',
                'nombre' => 'DARTH VADER ARTICULABLE',
                'slug' => Str::slug('DARTH VADER ARTICULABLE'),
                'descripcion' => 'Figura de Darth Vader. Tamaño 10 cm, material PVC. Articulable. Incluye sable.',
                'precio' => 30.00,
                'stock' => 5,
                'imagen1' => 'images/products/sw-001.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '10 cm',
                'incluye' => 'SABLE',
                'activo' => true,
                'category_id' => $starWarsId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sku' => 'SW-002',
                'nombre' => 'SET 8 FIGURAS HELLO KITTY',
                'slug' => Str::slug('SET 8 FIGURAS HELLO KITTY'),
                'descripcion' => 'Set de 8 figuras de Hello Kitty. Tamaño 8 cm. Incluye base.',
                'precio' => 25.00,
                'stock' => 5,
                'imagen1' => 'images/products/sw-002.jpg',
                'imagen2' => null,
                'imagen3' => null,
                'material' => 'PVC',
                'size' => '8 cm',
                'incluye' => '8 FIGURAS CON BASE',
                'activo' => true,
                'category_id' => $starWarsId,
                'precio_descuento' => null,
                'stock_minimo' => 5,
                'destacado' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insertar todos los productos
        DB::table('products')->insert($products);

        $this->command->info('✅ 73 productos insertados correctamente.');
    }
}